config/routes.rb
Rails.application.routes.draw do

root 'welcome#homepage'
get 'welcome/homepage'

resources :origins, only: [:index, :show]
resources :destinations, only: [:index, :show]

resources :facts, only: :index

namespace :charts do
  get "new-countries"
end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def homepage
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_1.html.erb
<!-- <div class="swiper-container hero-slider"> -->
  <div class="swiper-wrapper">
    <div class="swiper-slide hero-content-wrap">
      <img src="images/hero.jpg" alt="">

      <div class="hero-content-overlay position-absolute w-100 h-100">
        <div class="container h-100">
          <div class="row h-100">
            <div class="col-12 col-lg-8 d-flex flex-column justify-content-center align-items-start">
              <header class="entry-header">
                <h1>Refugees & Asylees</h1>
              </header><!-- .entry-header -->
              <div class="entry-content mt-4">
                <p>Globally, the forcibly displaced population increased in 2017 by 2.9 million.
By the end of the year, 68.5 million individuals were forcibly displaced worldwide as
a result of persecution, conflict, or generalized violence. As a result, the world’s
forcibly displaced population remained yet again at a record high.</p>
              </div><!-- .entry-content -->
            </div><!-- .col -->
          </div><!-- .row -->
        </div><!-- .container -->
      </div><!-- .hero-content-overlay -->
    </div><!-- .hero-content-wrap -->
  </div><!-- .swiper-wrapper -->

    <div class="pagination-wrap position-absolute w-100">
        <div class="container">
            <div class="swiper-pagination"></div>
        </div><!-- .container -->
    </div><!-- .pagination-wrap -->
<!--</div>--><!-- .hero-slider -->

app/views/welcome/_2.html.erb
<div class="home-page-icon-boxes">
  <div class="container">
    <div class="row">
      <div class="col-12 col-md-6 col-lg-4 mt-4 mt-lg-0">
        <div class="icon-box">
          <figure class="d-flex justify-content-center">
            <img src="images/tent.png" alt="">
            <img src="images/tent.png" alt="">
          </figure>

          <header class="entry-header">
            <h3><%= link_to "Facts & Terminologies", facts_path, class: "entry-title" %></h3>
          </header>

          <div class="entry-content">
            <p>68.5 million individuals have been forcibly displaced worldwide as a result of persecution, conflict, violence or human rights violations. We are now witnessing the highest levels of displacement on record.</p>
          </div>
        </div>
      </div>

      <div class="col-12 col-md-6 col-lg-4 mt-4 mt-lg-0">
        <div class="icon-box">
          <figure class="d-flex justify-content-center">
            <img src="images/sos.png" alt="">
            <img src="images/sos.png" alt="">
          </figure>

          <header class="entry-header">
            <h3><%= link_to "Countries of Origin for Refugees and Asylum Seekers", origins_path, class: "entry-title" %></h3>
          </header>

          <div class="entry-content">
            <p>A record 68.5 million people have been forced to flee their homes. Altogether, more than two-thirds (68 per cent) of all refugees worldwide came from just five countries. </p>
          </div>
        </div>
      </div>

      <div class="col-12 col-md-6 col-lg-4 mt-4 mt-lg-0">
        <div class="icon-box">
          <figure class="d-flex justify-content-center">
            <img src="images/road.png" alt="">
            <img src="images/road.png" alt="">
          </figure>

          <header class="entry-header">
            <h3><%= link_to "Countries of Destination for Refugees and Asylum Seekers", destinations_path, class: "entry-title" %></h3>
          </header>

          <div class="entry-content">
            <p>By the end of 2017, about 3.1 million people were awaiting a decision on their application for asylum, about half in developing regions. </p>
          </div>
        </div>
      </div>
    </div><!-- .row -->
  </div><!-- .container -->
</div><!-- .home-page-icon-boxes -->

app/views/welcome/_3.html.erb
<!-- <div class="home-page-welcome"> -->
    <div class="container">
        <div class="row">
            <div class="col-12 col-lg-6 order-2 order-lg-1">
                <div class="welcome-content">
                    <header class="entry-header">
                        <h2 class="entry-title">Statistics as of 2017</h2>
                    </header><!-- .entry-header -->

                    <div class="entry-content mt-5">
                        <p>In 2017, 16.2 million people were forcibly displaced as a result of persecution, conflict or generalized violence. This equates to 44,400 people every day and is the highest number recorded by UNHCR.</p>
                        <p>It brings the total worldwide population of forcibly displaced people to a new high of 68.5 million. This includes 40 million internally displaced people (IDPs), 25.4 million refugees and 3.1 million asylum-seekers.</p>
                        <p>The past decade has seen a substantial increase in the world’s forcibly displaced population, with the number standing at 42.7 million in 2007. The conflict in the Syrian Arab Republic (Syria) and significant displacements in Burundi, Central African Republic, the DRC, Iraq, Myanmar, South Sudan, Sudan, Ukraine and Yemen have driven an increase to the levels observed today.</p>
                    </div><!-- .entry-content -->

                </div><!-- .welcome-content -->
            </div><!-- .col -->

            <div class="col-12 col-lg-6 mt-4 order-1 order-lg-2">
                <img src="images/syr.jpg" alt="welcome">
            </div><!-- .col -->
        </div><!-- .row -->
    </div><!-- .container -->
<!-- </div> -->

app/views/welcome/homepage.html.erb
<div class="swiper-container hero-slider">
  <%= render '/welcome/1' %>
</div>

<div class="welcome-wrap">
  <%= render '/welcome/2' %>
</div>

<div class="home-page-welcome">
  <%= render '/welcome/3' %>
</div>